development:
  user: FELIX.VIAVANSI
  pass: felix.viavansi
  host: 192.168.10.115
  port: 8080
  post_ws:  /mds/doi
  metadata_ws:  /mds/metadata
  institution_prefix:  10.5072
production:
  user: FELIX.VIAVANSI
  pass: felix.viavansi
  host: 192.168.10.115
  port: 8080
  post_ws:  /mds/doi
  metadata_ws:  /mds/metadata
  institution_prefix:  10.5072  
